config/routes.rb
Rails.application.routes.draw do
  post 'signatures', to: 'signatures#create', as: :signatures
  get '', to: 'signatures#new', as: :new_signature
  get 'thankyou/:id', to: 'signatures#show', as: :signature
  get 'dashboard', to: 'signatures#dashboard', as: :dashboard

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signature.rb
class Signature < ApplicationRecord
  validates :name,
    presence: true,
    uniqueness: { scope: :zip_code,
                  message: "has already been registered for that zip code" }

  validates :zip_code,
    presence: true,
    format: { with: /\A[0-9]{5}\z/, message: "must be 5 digits" }

  after_validation :locate_zip_code

  private

  def locate_zip_code
    return if errors[:zip_code].any?
    zip_location = ZipLocation.find_by(zip_code: zip_code)
    if zip_location
      self.state = zip_location.state
    else
      errors.add(:zip_code, "couldn't be located")
    end
  end
end

app/models/zip_location.rb
class ZipLocation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  before_action :set_dashboard,
    unless: ->(controller) { controller.request.format.js? }

  # GET /
  def new
    @signature = Signature.new
    respond_to :html, :js
  end

  # POST /signatures
  def create
    @signature = Signature.new(signature_params)

    respond_to do |format|
      if @signature.save
        $my_redis.state_leaderboard_incr @signature.state
        format.html { redirect_to @signature }
        format.js { render :show }
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  # GET /thankyou/1
  def show
    @signature = Signature.find(params[:id])
    respond_to :html
  end

  # GET /dashboard
  def dashboard
    respond_to :json
  end

  private

  def set_dashboard
    (@signature_count, @leading_states) = $my_redis.dashboard
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def signature_params
    params.require(:signature).permit(:name, :zip_code)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StopLopa</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div id="information">
      <%= content_for :information %>
    </div>
    <br>
    <div id="interaction">
      <%= content_for :interaction %>
    </div>

    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/signatures.html.erb
<% content_for :information do %>
  <%= render 'dashboard' %>
<% end %>
<% content_for :interaction do %>
  <%= yield %>
<% end %>
<%= render template: 'layouts/application' %>

app/views/signatures/_dashboard.html.erb
<h1>Dashboard</h1>

<table>
  <tbody>
    <tr>
      <td>
        <p>Signature Count</p>
      </td>
      <td>
        <ul>
          <li id="signature_count">
            <%= @signature_count %>
          </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>
        <p>Leading States</p>
      </td>
      <td>
        <ol id="leading_states">
          <% @leading_states.each do |state| %>
            <li><%= state %></li>
          <% end %>
        </ol>
      </td>
    </tr>
  </tbody>
</table>

app/views/signatures/_form.html.erb
<h1>New Signature</h1>
<%= form_with(model: signature) do |form| %>
  <% if signature.errors.any? %>
    <div id="error_explanation">
      <h2>Please be advised that:</h2>
      <ul>
        <% signature.errors.messages.each do |field, messages| %>
          <li><%= field.to_s.humanize + ' ' + messages[0] %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :signature_name %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code, id: :signature_zip_code %>
  </div>

  <div class="actions">
    <%= form.submit data: { "disable-with": "Registering..." } %>
  </div>
<% end %>

app/views/signatures/_signature.html.erb
<h1>Thank You</h1>

<p>
Your signature, <%= @signature.name %>, has been added to the list
</p>

<%= link_to 'Click here to add another signature', new_signature_path, remote: true %>

app/views/signatures/new.html.erb
<%= render 'form', signature: @signature %>

app/views/signatures/new.js.erb
document.querySelector('#interaction')
  .innerHTML = ('<%= j render('form', signature: @signature) %>')

app/views/signatures/show.html.erb
<%= render @signature %>

app/views/signatures/show.js.erb
document.querySelector('#interaction')
  .innerHTML = ('<%= j render(@signature) %>')